import {faker} from "@faker-js/faker";
import {sample} from "lodash";
import dayjs from "dayjs";

const projects = [
    {
        id: faker.datatype.uuid().substring(0, 7),
        name: faker.lorem.words(3),
        phase: sample(['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4']),
        btsHead: faker.lorem.word(2).toUpperCase(),
        btomHead: faker.lorem.word(2).toUpperCase(),
        portfolioHead: faker.lorem.word(2).toUpperCase(),
        projectManager: faker.lorem.word(2).toUpperCase(),
        deliveryHead: faker.lorem.word(2).toUpperCase(),
        deliveryManager: faker.lorem.word(2).toUpperCase(),
        businessSegment: sample(['Group Retail', 'Business']),
        team: sample(['DB', 'TMRW', 'CP', 'CEW', 'IDB']),
        startDate: faker.date.between('2020-01-01T00:00:00.000Z', '2022-11-01T00:00:00.000Z').toLocaleDateString(),
        completionDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        strategic: sample(['Strategic', 'BAU Partner']),
        approvalComm: faker.lorem.word(3).toUpperCase(),
        lastUpdatedBy: faker.name.firstName(),
        lastUpdatedDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        approvalDate: dayjs('2022-10-25').format('DD/MM/YYYY'),
        isVerified: faker.datatype.boolean(),
        status: 'Completed'
    },
    {
        id: faker.datatype.uuid().substring(0, 7),
        name: faker.lorem.words(3),
        phase: sample(['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4']),
        btsHead: faker.lorem.word(2).toUpperCase(),
        btomHead: faker.lorem.word(2).toUpperCase(),
        portfolioHead: faker.lorem.word(2).toUpperCase(),
        projectManager: faker.lorem.word(2).toUpperCase(),
        deliveryHead: faker.lorem.word(2).toUpperCase(),
        deliveryManager: faker.lorem.word(2).toUpperCase(),
        businessSegment: sample(['Group Retail', 'Business']),
        team: sample(['DB', 'TMRW', 'CP', 'CEW', 'IDB']),
        startDate: faker.date.between('2020-01-01T00:00:00.000Z', '2022-11-01T00:00:00.000Z').toLocaleDateString(),
        completionDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        strategic: sample(['Strategic', 'BAU Partner']),
        approvalComm: faker.lorem.word(3).toUpperCase(),
        lastUpdatedBy: faker.name.firstName(),
        lastUpdatedDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        approvalDate: dayjs('2022-10-25').format('DD/MM/YYYY'),
        isVerified: faker.datatype.boolean(),
        status: 'On-Hold'
    },
    {
        id: faker.datatype.uuid().substring(0, 7),
        name: faker.lorem.words(3),
        phase: sample(['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4']),
        btsHead: faker.lorem.word(2).toUpperCase(),
        btomHead: faker.lorem.word(2).toUpperCase(),
        portfolioHead: faker.lorem.word(2).toUpperCase(),
        projectManager: faker.lorem.word(2).toUpperCase(),
        deliveryHead: faker.lorem.word(2).toUpperCase(),
        deliveryManager: faker.lorem.word(2).toUpperCase(),
        businessSegment: sample(['Group Retail', 'Business']),
        team: sample(['DB', 'TMRW', 'CP', 'CEW', 'IDB']),
        startDate: faker.date.between('2020-01-01T00:00:00.000Z', '2022-11-01T00:00:00.000Z').toLocaleDateString(),
        completionDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        strategic: sample(['Strategic', 'BAU Partner']),
        approvalComm: faker.lorem.word(3).toUpperCase(),
        lastUpdatedBy: faker.name.firstName(),
        lastUpdatedDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        approvalDate: dayjs('2022-10-25').format('DD/MM/YYYY'),
        isVerified: faker.datatype.boolean(),
        status: 'WIP'
    },
    {
        id: faker.datatype.uuid().substring(0, 7),
        name: faker.lorem.words(3),
        phase: sample(['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4']),
        btsHead: faker.lorem.word(2).toUpperCase(),
        btomHead: faker.lorem.word(2).toUpperCase(),
        portfolioHead: faker.lorem.word(2).toUpperCase(),
        projectManager: faker.lorem.word(2).toUpperCase(),
        deliveryHead: faker.lorem.word(2).toUpperCase(),
        deliveryManager: faker.lorem.word(2).toUpperCase(),
        businessSegment: sample(['Group Retail', 'Business']),
        team: sample(['DB', 'TMRW', 'CP', 'CEW', 'IDB']),
        startDate: faker.date.between('2020-01-01T00:00:00.000Z', '2022-11-01T00:00:00.000Z').toLocaleDateString(),
        completionDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        strategic: sample(['Strategic', 'BAU Partner']),
        approvalComm: faker.lorem.word(3).toUpperCase(),
        lastUpdatedBy: faker.name.firstName(),
        lastUpdatedDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        approvalDate: dayjs('2022-11-15').format('DD/MM/YYYY'),
        isVerified: faker.datatype.boolean(),
        status: 'WIP'
    },
    {
        id: faker.datatype.uuid().substring(0, 7),
        name: faker.lorem.words(3),
        phase: sample(['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4']),
        btsHead: faker.lorem.word(2).toUpperCase(),
        btomHead: faker.lorem.word(2).toUpperCase(),
        portfolioHead: faker.lorem.word(2).toUpperCase(),
        projectManager: faker.lorem.word(2).toUpperCase(),
        deliveryHead: faker.lorem.word(2).toUpperCase(),
        deliveryManager: faker.lorem.word(2).toUpperCase(),
        businessSegment: sample(['Group Retail', 'Business']),
        team: sample(['DB', 'TMRW', 'CP', 'CEW', 'IDB']),
        startDate: faker.date.between('2020-01-01T00:00:00.000Z', '2022-11-01T00:00:00.000Z').toLocaleDateString(),
        completionDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        strategic: sample(['Strategic', 'BAU Partner']),
        approvalComm: faker.lorem.word(3).toUpperCase(),
        lastUpdatedBy: faker.name.firstName(),
        lastUpdatedDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        approvalDate: dayjs('2022-11-10').format('DD/MM/YYYY'),
        isVerified: faker.datatype.boolean(),
        status: 'On-Hold'
    },
    {
        id: faker.datatype.uuid().substring(0, 7),
        name: faker.lorem.words(3),
        phase: sample(['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4']),
        btsHead: faker.lorem.word(2).toUpperCase(),
        btomHead: faker.lorem.word(2).toUpperCase(),
        portfolioHead: faker.lorem.word(2).toUpperCase(),
        projectManager: faker.lorem.word(2).toUpperCase(),
        deliveryHead: faker.lorem.word(2).toUpperCase(),
        deliveryManager: faker.lorem.word(2).toUpperCase(),
        businessSegment: sample(['Group Retail', 'Business']),
        team: sample(['DB', 'TMRW', 'CP', 'CEW', 'IDB']),
        startDate: faker.date.between('2020-01-01T00:00:00.000Z', '2022-11-01T00:00:00.000Z').toLocaleDateString(),
        completionDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        strategic: sample(['Strategic', 'BAU Partner']),
        approvalComm: faker.lorem.word(3).toUpperCase(),
        lastUpdatedBy: faker.name.firstName(),
        lastUpdatedDate: faker.date.between('2020-01-01T00:00:00.000Z', '2023-01-01T00:00:00.000Z').toLocaleDateString(),
        approvalDate: dayjs('2022-10-10').format('DD/MM/YYYY'),
        isVerified: faker.datatype.boolean(),
        status: 'Completed'
    }
]

export default projects;